version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
        environment: 
            - SENDGRID_KEY=${SENDGRID_KEY}
            - KABOO_CONTACT_EMAIL=${KABOO_CONTACT_EMAIL}
            - WEB_ADDRESS=${WEB_ADDRESS}
    composer:
        restart: 'no'
        image: composer/composer:latest
        command: install
        volumes:
            - ./app:/app
        working_dir: /app/public